### ISSUE TITLE
about input data in SSL process

### ISSUE THREAD

**Issue by GuobinZhangTJU** [JunMa11/AbdomenCT-1K#1]
Hi, Jun, perfect and selfless work, and admire you.
I hope that the paper will be published as soon as possible!
Can I ask you two questions?
Q1: in “4.2 Semi-supervised organ segmentation benchmark”, before this step, all four organs’ GTs have been labeled. I want to know, in this SSL step, the input GT is only one organ, or all four labeled organs during training?
Q2: also in section 4.2 about SSL, you employed model is nnUNet, so the input batch size is still 2?
Thanks, waiting for your reply, and wish you many scientific achievements.

**Comment by JunMa11** [comment]
Hi @GuobinZhangTJU ,

Thanks for your kind words.

Q1. The input is four organs.

Q2. Yes, the batch size is 2.

**Comment by GuobinZhangTJU** [comment]
> Hi @GuobinZhangTJU ,
> 
> Thanks for your kind words.
> 
> Q1. The input is four organs.
> 
> Q2. Yes, the batch size is 2.

Got it ~~ Thnaks a lot ~~~Hope the paper will be published as soon as possible again~~
