### ISSUE TITLE
GIF 3D segmentation

### ISSUE THREAD

**Issue by Chop1** [JunMa11/AbdomenCT-1K#10]
Do you mind sharing the gist to create the "3D rotating view" segmentation gif you use in your readme ? It's pretty cool!
Thanks in advance.

**Comment by JunMa11** [comment]
Hi @Chop1 ,

Of course, it's not a secret:)

We use the screen capture module in 3D slicer to get the gif
https://www.slicer.org/wiki/Documentation/4.6/Modules/ScreenCapture
