### ISSUE TITLE
Subject origins

### ISSUE THREAD

**Issue by CamielKerckhaert** [JunMa11/AbdomenCT-1K#11]
Could you perhaps share with us which subjects (1-1062) in the dataset come from which dataset (NIH, KiTS, LiTS, MSD, etc.)? Thank you in advance!

**Comment by JunMa11** [comment]
Hi @CamielKerckhaert ,

Thanks for your interest.
Unfortunately, we do not have a plan to release the center info.
Please refer to https://github.com/JunMa11/AbdomenCT-1K/issues/4

**Comment by CamielKerckhaert** [comment]
Thanks for your reaction! 
However, i didn't mean the center information, just the datasets (NIH, KiTS, LiTS, MSD).
I am doing an internship in a company, and therefore I cannot use the data from the KiTS dataset which has a non-commercial license. I would like to exclude the KiTS data from the data that I am using. Could you tell me which subjects are from the KiTS dataset? Thank you.

**Comment by JunMa11** [comment]
@CamielKerckhaert 
It seems that the license has been changed to CC
https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=61081171#61081171b28296bcc57c4d9b97bd5b55d766cc9c
