### ISSUE TITLE
50 cases with 12 annotated organs  dataset only has 48 niis

### ISSUE THREAD

**Issue by hxshust** [JunMa11/AbdomenCT-1K#12]
hi，thank you for your work on Abdominal organ dataset.
 When I  download the dataset of 50 cases with 12 annotated organs from Dropbox，I find Image only has 48(3-50) niis while Mask has 50(1-50) niis.

Maybe you can upload the missing nii to the dropbox，hope this won't bother you.

**Comment by JunMa11** [comment]
Hi @hxshust 
Thanks for the reminder.
I have uploaded it just now:)
