### ISSUE TITLE
about noisy label

### ISSUE THREAD

**Issue by SakurajimaMaiii** [JunMa11/AbdomenCT-1K#13]
Thanks for this great contribution.
It is noticed that 773 cases with pseudo tumor labels without groudn truth. Could you tell me where I can find ground truth of pseudo tumor labels (_i.e. the tumor label of Case_00001-00773_) for noisy label research.

**Comment by JunMa11** [comment]
Hi @SakurajimaMaiii ,

Thanks for your interest.

Unfortunately, we do not have ground truth. 
We annotate all the possible lesions. However, to obtain the ground truth, one may need pathological examination results.

Hope the answer helps and Happy new year:)

**Comment by SakurajimaMaiii** [comment]
> 

Thanks for your help.
