### ISSUE TITLE
Data link seems not working

### ISSUE THREAD

**Issue by duducheng** [JunMa11/AbdomenCT-1K#14]

**Comment by JunMa11** [comment]
Hi @duducheng ,

Thanks for the feedback. Dropbox is not stable (even if we have paid the money to enlarge the space) when many users download the data. We will try to move the data to zenodo in this week.

![1643071121(1)](https://user-images.githubusercontent.com/19947331/150888850-9473980a-b28e-440f-bc6c-ec0394985f60.png)
