### ISSUE TITLE
How to download 773 cases with pseudo tumor labels without Baidu account

### ISSUE THREAD

**Issue by sirfoga** [JunMa11/AbdomenCT-1K#15]
First of all thanks for your effort in making this incredible contribution to medical analysts! However I cannot find a way to download the 773 cases with pseudo tumor labels without Baidu account (I'm in Austria, with an Austrian mobile number) .. is there a Dropbox/MEGA/alternative link available?

Thanks!

**Comment by JunMa11** [comment]
Hi @sirfoga ,

Thanks for your interest.
I used dropbox but it is not stable.
I just added Google drive download link. Please let me know if you have any further problems.

Best,
Jun
