### ISSUE TITLE
Image preprocessing and normalization for training! 

### ISSUE THREAD

**Issue by adigasu** [JunMa11/AbdomenCT-1K#16]
Hi,

Thanks for this incredible collection of abdominal data.
I was wondering what kind of preprocessing is used in experiments in paper (normalization, resolution or image size, if patchwise then input size). This information will greatly help everyone to relate their results to the one in the paper.

Thanks,
Sukesh

**Comment by JunMa11** [comment]
Hi @adigasu ,

Thanks for your interest.

All these settings are the default settings in nnUNet without any changes. 

Best,
Jun
