### ISSUE TITLE
detection abdomen CT scan

### ISSUE THREAD

**Issue by kimjisoo12** [JunMa11/AbdomenCT-1K#17]
Hello, I'd like to ask you a question. I feel that some data ct sequences are not just abdomen. Is there an automatic method to extract abdominal ct sequences from all ct sequences?

**Comment by JunMa11** [comment]
Hi @kimjisoo12, 
We do not recommend extracting only the abdomen part. In real practice, we need to deal with whole-body CT scans.
In other words, abdomen CT refers to the CT scans that contain abdominal organs. It's not the CT scan that only contains abdominal organs.
