### ISSUE TITLE
Subject overlaps between fully supervised and semi-supervised datasets?

### ISSUE THREAD

**Issue by seannz** [JunMa11/AbdomenCT-1K#18]
Dear AbdomenCT-1K Team,

Thank you for making this dataset publicly available to the medical imaging research community—I was wondering:

Are there any subject overlaps between the training (Tr) / testing (Ts) sets of fully (F) supervised and semi (S) -supervised datasets? More specifically, are there overlaps between the following pairs of datasets? TrF–TrS, TrF-TsS, TrS–TsF, TsF–TsS

Thank you,

Sean I Young

**Comment by JunMa11** [comment]
Yes, they have overlap. For each benchmark, please only use the training data in this benchmark.
