### ISSUE TITLE
百度云提供的预训练模型该怎么使用？

### ISSUE THREAD

**Issue by xhw205** [JunMa11/AbdomenCT-1K#19]
直接用来推理不可以吗？
报错：
starting prediction...
inference done. Now waiting for the segmentation export to finish...
WARNING! Cannot run postprocessing because the postprocessing file is missing. Make sure to run consolidate_folds in the        output folder of the model first!
The folder you need to run this in is /home/xhw205/nnUNetFrame/DATASET/nnUNet_trained_models/nnUNet/3d_fullres/Task003_L       iver/nnUNetTrainerV2__nnUNetPlansv2.1

**Comment by JunMa11** [comment]
it's hard to know the reason with limited info.
Could you please provide all the details you have done?

**Comment by JunMa11** [comment]
BTW, docker would be a more convenient way to use the trained model. You do not need to set up the environment again.

**Comment by xhw205** [comment]
Thanks. I have found the answer in [nnUNet issue](https://github.com/MIC-DKFZ/nnUNet/issues/1083)
