### ISSUE TITLE
about normalized surface Dice (NSD)

### ISSUE THREAD

**Issue by GuobinZhangTJU** [JunMa11/AbdomenCT-1K#2]
Hi, Jun, it is mentioned that both Dice and NSD are important in medical segmentation, did you try to employ NSD as the segmentation loss?, and how about the performance in segmentation using the NSD as the segmentation loss?
Thanks, waiting for your reply~~~

**Comment by JunMa11** [comment]
Hi @GuobinZhangTJU ,

Not yet. It is non-trivial to formulate the NSD as a segmentation loss.

**Comment by GuobinZhangTJU** [comment]
> Hi @GuobinZhangTJU ,
> 
> Not yet. It is non-trivial to formulate the NSD as a segmentation loss.

Got it, many thanks for your reply.

**Comment by GuobinZhangTJU** [comment]
Hi, Jun, sorry to bother you again, can l ask:
what is the tolerance value t you used in the  in NSD when do the evaluation? 
and the calculation is the "("surface dice at 1mm:      {}".format(compute_surface_dice_at_tolerance(surface_distances, 0.1)))" in your provided link?
Many thanks~~ waiting for your reply~

**Comment by JunMa11** [comment]
Hi @GuobinZhangTJU 

We use the default 1mm.

**Comment by GuobinZhangTJU** [comment]
> Hi @GuobinZhangTJU
> 
> We use the default 1mm.

Hi, Jun ,thanks~  I test two model on one slice, and the result is :

# average surface distance: (0.27396065571216255, 0.27178411686094217) mm
# hausdorff (100%):         11.313708498984761 mm
# hausdorff (95%):          2.23606797749979 mm
# surface overlap at 1mm:   (0.9340116161156132, 0.9397420673354426)
# surface dice at 1mm:      0.9368871980048996
# volumetric dice:          0.9055971111684292

# average surface distance: (0.1775179797064372, 0.052221118743957386) mm
# hausdorff (100%):         7.0 mm
# hausdorff (95%):          1.0 mm
# surface overlap at 1mm:   (0.9551812677470284, 0.9836400942986598)
# surface dice at 1mm:      0.9692481329429863
# volumetric dice:          0.9398063334205705

I found that the gap between dice is about 0.03, (0.9055 -- 0.9398 )
and the gap between NSD is also about 0.03, (0.9368 -- 0.9692)
here ia the comparion of the predicted mask based on the uwo model:

![1619764090(1)](https://user-images.githubusercontent.com/42600942/116657039-546a4e00-a9c0-11eb-98cf-987ee3a5ba14.jpg)

Do you think it is reasonable?  many thanks,  Jun~

**Comment by JunMa11** [comment]
Hi @GuobinZhangTJU ，

> Do you think it is reasonable? 

Yes. I think so because the boundary mismatch in the left image is not very large.

BTW, if you want to increase the gap of NSD, you can add some isolated outliers and increase the boundary mismatch in the left image.

**Comment by GuobinZhangTJU** [comment]
> Hi @GuobinZhangTJU ，
> 
> > Do you think it is reasonable?
> 
> Yes. I think so because the boundary mismatch in the left image is not very large.
> 
> BTW, if you want to increase the gap of NSD, you can add some isolated outliers and increase the boundary mismatch in the left image.

Got it, very thanks ~~~ Jun~~
