### ISSUE TITLE
Question about the source of the ct volume for the AbdomenCT1K dataset

### ISSUE THREAD

**Issue by ies9357** [JunMa11/AbdomenCT-1K#21]
I was wondering if the ct volumes of one of the AbdomenCT1K datasets you have provided are labeled to indicate which dataset they are from: LiTS, KiTS, MSD Spleen, MSD Pancreas, NIH Pancreas, etc. For example, I was wondering which dataset the ct volume named Case_00413_0000.nii.gz that I downloaded from your GitHub came from.

**Comment by JunMa11** [comment]
Thanks for your interest.

It is our purpose to hide the center information, which aims to avoid participants find the ground truth in the benchmarks.

If you want to evaluate the generalization ability of the algorithm with the multi-center data. Just joining the benchmark is the easiest way:).
