### ISSUE TITLE
Question about the invalid Baidu Yun download link

### ISSUE THREAD

**Issue by zhaoziheng** [JunMa11/AbdomenCT-1K#22]
The dataset looks awesome but the download speed from zenodo seems to be too slow ...... 
The share link from Baidu Yun is invalid now, could you please update it? Thanks a lot.

**Comment by JunMa11** [comment]
Hi @zhaoziheng ,

It seems that baidu netdisk is not stable if many ppl download the data. 

Please use the zenodo link to download the data.
