### ISSUE TITLE
About the tumor type

### ISSUE THREAD

**Issue by peterant330** [JunMa11/AbdomenCT-1K#26]
Thanks for this great work.

I want to ask about the pseudo tumor label. Does it contains any tumor such as colon cancer and stomach cancer, or just the cancer in the four organs?

And I am also wondering if the dataset have overlap with the dataset in Flare-2022 and 2023?

Thank you very much!

**Comment by JunMa11** [comment]
Hi @peterant330 ,

1. We don't have the tumor site information. If you are interested in tumor segmentation, welcome to join the FLARE24 challenge: https://www.codabench.org/competitions/2319/

> Note: these pseudo tumor labels were generated by old nnU-Net. We would recommend training the latest nnUNet model to generate new pseudo tumor labels.  

2. This dataset has been fully included in the FLARE challenges.

**Comment by peterant330** [comment]
Thanks for your reply.

Could you explain more about the pseudo tumor label generation process? Is it generated by a nnU-Net trained with pan-cancer segmentation dataset such as FLARE23?

**Comment by JunMa11** [comment]
no. it was generated by trained nnunetv1 models on list, kits, and msd-pancreas datasets.
