### ISSUE TITLE
可以考虑将来自LiTS中的20个Spacing为（1.0,1.0,1.0）的卷替换为使用3DIRCADB数据集的20个训练集

### ISSUE THREAD

**Issue by QianMuXiao** [JunMa11/AbdomenCT-1K#27]
LiTS数据集中的liver28-47号这20个卷来和3D-IRCADB数据集的训练集重合，为了区别，LiTS数据集将这20个卷的Spacing转为了（1.0,1.0,1.0），像素矩阵的维度完全相同，这20个卷对应abdomenCT-1K中的卷号如下：

Case_00276_0000.nii.gz (1.0, 1.0, 1.0)
Case_00282_0000.nii.gz (1.0, 1.0, 1.0)
Case_00576_0000.nii.gz (1.0, 1.0, 1.0)
Case_00078_0000.nii.gz (1.0, 1.0, 1.0)
Case_00273_0000.nii.gz (1.0, 1.0, 1.0)
Case_00575_0000.nii.gz (1.0, 1.0, 1.0)
Case_00284_0000.nii.gz (1.0, 1.0, 1.0)
Case_00281_0000.nii.gz (1.0, 1.0, 1.0)
Case_00275_0000.nii.gz (1.0, 1.0, 1.0)
Case_00462_0000.nii.gz (1.0, 1.0, 1.0)
Case_00577_0000.nii.gz (1.0, 1.0, 1.0)
Case_00286_0000.nii.gz (1.0, 1.0, 1.0)
Case_00283_0000.nii.gz (1.0, 1.0, 1.0)
Case_00277_0000.nii.gz (1.0, 1.0, 1.0)
Case_00274_0000.nii.gz (1.0, 1.0, 1.0)
Case_00578_0000.nii.gz (1.0, 1.0, 1.0)
Case_00280_0000.nii.gz (1.0, 1.0, 1.0)
Case_00278_0000.nii.gz (1.0, 1.0, 1.0)
Case_00285_0000.nii.gz (1.0, 1.0, 1.0)
Case_00574_0000.nii.gz (1.0, 1.0, 1.0)

**Comment by QianMuXiao** [comment]
另外可以考虑扩充MSD_Task08，肝脏血管分割数据集进行多标签增强

**Comment by JunMa11** [comment]
Hi @QianMuXiao ，

Thanks for your great notes. 

Based on the results in the MICCAI Challenges, the winning solutions are very robust to these spacings.

We have expanded the dataset to 10K. Welcome to join the MICCAI FLARE 2024 Challenge. 
https://www.codabench.org/competitions/2319/
