### ISSUE TITLE
Thank you for this great contribution!

### ISSUE THREAD

**Issue by YoelShoshan** [JunMa11/AbdomenCT-1K#3]
This seems like an incredible contribution to the medical imaging community :)
Do you have any estimates of when it will be released?

**Comment by JunMa11** [comment]
Hi @YoelShoshan ,

Thanks for your interest very much:)

Part of the dataset has been released in MICCAI FLARE21 Challenge
https://flare.grand-challenge.org/


The whole dataset will be available when the paper is accepted.
