### ISSUE TITLE
The center information for AbdomenCT-1K

### ISSUE THREAD

**Issue by BurningFr** [JunMa11/AbdomenCT-1K#4]
Thanks a lot for this awesome work which release a large dataset for the Abdomen organ segmentation task. And in the paper, you mention that these cases are from 12 different centers. Could you please release the center information or the correspondence between the sample and the original datasets.

**Comment by JunMa11** [comment]
Hi @BurningFr ,

Thanks for your interest.

It is our purpose to hidden the center information, which aims to avoid participants find the ground truth in the benchmarks.

If you want to evaluate the generalization ability of the algorithm with the multi-center data. Just join the benchmark is the easiest way:).

Best regards,
Jun

**Comment by BurningFr** [comment]
Got it! Thanks:)
