### ISSUE TITLE
你好，我通过dropbox下载每次下载到最后就报错了，尝试了很多次多出现了这个问题，请问能不能国内百度网盘的地址了？多谢了

### ISSUE THREAD

**Issue by rw1995** [JunMa11/AbdomenCT-1K#5]
你好，JumMa， 十分感谢你提供的数据集。但是此处我遇到了一个问题，导致我Image数据集下载出现了问题。
我通过dropbox下载每次下载到最后就报错了，尝试了很多次, 对于0-1000的数据都出现了这个问题。这可能和数据集过大有关， 请问能不能国内百度网盘的下载地址了？多谢了。
![image](https://user-images.githubusercontent.com/37976371/128700513-f730988a-d3fa-4f2f-b635-5957f3894ab2.png)

**Comment by JunMa11** [comment]
您好，
可能是您那边网络的问题，我们这边测试了dropbox下载链接正常。
我们最近非常忙，上传到百度网盘需要一定时间，争取下周末提供给您。

**Comment by rw1995** [comment]
> 您好，
> 可能是您那边网络的问题，我们这边测试了dropbox下载链接正常。
> 我们最近非常忙，上传到百度网盘需要一定时间，争取下周末提供给您。

多谢你了，JunMa

**Comment by JunMa11** [comment]
Hi @rw1995 

We have added the baidu netdisk in the download form.

https://forms.gle/XDrxSgoCXs3jzn8U7

**Comment by rw1995** [comment]
> Hi @rw1995
> 
> We have added the baidu netdisk in the download form.
> 
> https://forms.gle/XDrxSgoCXs3jzn8U7

Thanks， JunMa

**Comment by tanbin5070** [comment]
Hello,  JunMa.  can you update the baidu link of data again. The original link failed
 thanks

**Comment by tanbin5070** [comment]
I can't use Dropbox here. It can't be installed properly. So could you please send a link to Baidu cloud again

**Comment by JunMa11** [comment]
Hi @tanbin5070 
We test the Baidu netdisk download link just now. It works well! Please check your network.

**Comment by tanbin5070** [comment]
@JunMa11 
Yes, baidu cloud link can be used now. Thank you very much

**Comment by lichen14** [comment]
Hi,  @Junma @JunMa11 , I just registered but found that the Baidu link was invalid again, can you share it? thx

**Comment by JunMa11** [comment]
Hi @lichen14 ,

I try the link just now and it works. Could you please try to copy the link to your chrome/edge browser or open it on your mobile phone and save it to your baidu netdisk?

I also invite two people to test, both of them work.

**Comment by lichen14** [comment]
Hi @JunMa11 , thanks for your reply. 
I just tried again and this link works on Safari, but it doesn’t work on chrome. Maybe there were some errors in my PC. 
Thank you for your work!  😄
