### ISSUE TITLE
Annotation data does not correspond to image data

### ISSUE THREAD

**Issue by shchojj** [JunMa11/AbdomenCT-1K#6]
First of all, thank you for the AbdomenCT-1K dataset, which really solved the problem of partition generalization I encountered.However, when I downloaded the data, I found that the Mask data did not correspond to the Image data, for example, the Image data was 1~1000, but the maximum file of the Mask data was 1062, and the total number of mask was 1000. How to correspond to these data?

**Comment by JunMa11** [comment]
> the Image data was 1~1000, 

We invite some guys to download the dataset but we can not reproduce your problem. The number of image cases is 1062.

> When I read data through SimpleItk, I said "No Orthonormal Definition found!"

It is interesting. Basically, we usually use itk-snap and nibabel to handle the data. Both of them work well with this case.

**Comment by shchojj** [comment]
Thank you for your reply. Sorry for that, I didn't unzip the "Case_1000-.7z" file. However, there are only 1000 Mask data, which does not correspond to the number of image data (1-1063).  However, a cursory reading of the data set still shows an error  "No Orthonormal Definition found!" Data such as the following:
['00433','00405','00051','00702','00232','00423','00432','00401','00240','00244','00217','00403','00438','00687','00213','00549','00251','00681','00205','00221','00756','00448','00011','00049','00712','00021','00057','00249','00238','00219']

**Comment by JunMa11** [comment]
Please read the `Readme`. we keep the remained label hidden in the grandchallenge.
You can obtain the evaluation results by submitting the results.

Does nibabel also have this problem?

**Comment by shchojj** [comment]
Thank you for your patience.
Do you mean the "HiddenTestSet1063-1112.txt" file?50 cases (1063~1112) of Mark data are hidden, but there is no intersection with Image dataset 1~1062.Moreover, there are 63 marks difference between Mark data and Image data.
Yep, "nibabel" reads fine, I prefer "Simpleitk" to read and write data, maybe I should switch to "nibabel" which is more compatible.

**Comment by JunMa11** [comment]
Please check the readme file in the mask folder

```
To avoid the ground truth leakage in AbdomenCT-1K benchmarks, we made 1000 annotations publicly available. 
The hidden annotations can be accessed on the grand-challenge by submitting your segmentation results.
- Fully superivsed learning: https://abdomenct-1k-fully-supervised-learning.grand-challenge.org/
- Semi-superivsed learning: https://abdomenct-1k-semi-supervised-learning.grand-challenge.org/
- Weakly supervised learning: https://abdomenct-1k-weaklysupervisedlearning.grand-challenge.org/
- Continual learning: https://abdomenct-1k-continual-learning.grand-challenge.org/ 
```
