### ISSUE TITLE
Problem of Subtask 2 training set in AbdomenCT-1K Fully Supervised Learning Benchmark

### ISSUE THREAD

**Issue by liqiang3235** [JunMa11/AbdomenCT-1K#7]
In the Subtask 2 of AbdomenCT-1K Fully Supervised Learning Benchmark, it said that the training set is adapted from MSD Pancreas (281 cases) , LiTS (40 cases) , and KiTS (40 cases), where the cases are from different phases. However, after checking the data set, I found that the training set consists of MSD Pancreas (281 cases) , MSD Spleen (9 cases), LiTS (27 cases) , and KiTS (44 cases).

**Comment by JunMa11** [comment]
Hi @liqiang3235 ，

Thank you so much for pointing out this critical issue. We are so sorry for uploading the wrong folder. The data has been updated in the baidu net disk just now. And we will also check all the other uploaded datasets.

Best,
Jun

**Comment by JunMa11** [comment]
@liqiang3235 
Any further questions?
