### ISSUE TITLE
A few cases miss spleen annotations

### ISSUE THREAD

**Issue by liqiang3235** [JunMa11/AbdomenCT-1K#8]
In masks of the Whole Dataset, I found that  two cases (Case_00219.nii.gz, Case_00656.nii.gz) miss spleen annotations. Why?

**Comment by JunMa11** [comment]
Could you please check the image?
These two image cases do not have the spleen.

**Comment by liqiang3235** [comment]
I checked the images corresponding to the annotations. Indeed, those two images do not have spleen.

**Comment by JunMa11** [comment]
@liqiang3235 
Yes, that's it:)

**Comment by JunMa11** [comment]
Hi @liqiang3235 ,

Are there any further questions?

**Comment by liqiang3235** [comment]
NQ, thanks!
